<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-6QCN0R3" failures="0" tests="1" name="day3.timeout" time="7.080" errors="1" timestamp="27 May 2021 04:14:44 GMT" skipped="0">
  <testcase classname="day3.timeout" name="function41" time="7.080">
    <error message="Method day3.timeout.function41() didn&#039;t finish within the time-out 7000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method day3.timeout.function41() didn't finish within the time-out 7000
]]>
    </error>
  </testcase> <!-- function41 -->
</testsuite> <!-- day3.timeout -->
